// ─── JSX Generator for After Effects ExtendScript ───────
// Generates .jsx scripts that After Effects can execute via aerender
// to open a project, set variable values, replace footage, render, and quit.
//
// This is the canonical implementation shared between the server and agent.

import { RenderJob } from "./api-client";

// ─── Types ──────────────────────────────────────────────

export interface JsxVariable {
  layerName: string;
  effectName: string;
  effectType: string;
  value: string | number;
}

export interface JsxFootageReplacement {
  originalName: string;
  newFilePath: string;
}

export interface JsxGeneratorInput {
  aepFilePath: string;
  outputAepPath: string;
  outputMp4Path: string;
  exportCompName: string;
  variables: JsxVariable[];
  footageReplacements: JsxFootageReplacement[];
}

// ─── Helpers ────────────────────────────────────────────

function escapeJsString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/'/g, "\\'")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

function normalizePath(p: string): string {
  return p.replace(/\\/g, "/");
}

function formatValue(effectType: string, value: string | number): string {
  switch (effectType.toLowerCase()) {
    case "slider":
      return typeof value === "number"
        ? String(value)
        : `parseFloat("${escapeJsString(String(value))}")`;
    case "checkbox":
      if (typeof value === "number") return value ? "1" : "0";
      if (typeof value === "string") {
        const lower = value.toLowerCase();
        if (
          lower === "true" ||
          lower === "1" ||
          lower === "yes" ||
          lower === "on"
        )
          return "1";
        if (
          lower === "false" ||
          lower === "0" ||
          lower === "no" ||
          lower === "off"
        )
          return "0";
        return `parseInt("${escapeJsString(value)}", 10)`;
      }
      return String(value);
    case "color":
      return String(value);
    default:
      return typeof value === "number"
        ? String(value)
        : `"${escapeJsString(String(value))}"`;
  }
}

function sanitizeVarName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^(\d)/, "_$1")
    .replace(/_+/g, "_")
    .replace(/_$/, "");
}

function getEffectPropertyName(effectType: string): string {
  switch (effectType.toLowerCase()) {
    case "slider":
      return "Slider";
    case "checkbox":
      return "Checkbox";
    case "color":
      return "Color";
    case "point":
      return "Point";
    case "layer":
      return "Layer";
    case "angle":
      return "Angle";
    case "dropdown":
      return "Menu";
    default:
      return effectType;
  }
}

// ─── JSX Code Generation ────────────────────────────────

export function generateJsx(input: JsxGeneratorInput): string {
  const {
    aepFilePath,
    outputAepPath,
    outputMp4Path,
    exportCompName,
    variables,
    footageReplacements,
  } = input;

  const lines: string[] = [];

  // ── Header & Error Handling ──
  lines.push("// Auto-generated ExtendScript for After Effects");
  lines.push("// Generated by AE Render Automat");
  lines.push(`// Date: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("// Suppress all dialogs");
  lines.push("app.beginSuppressDialogs();");
  lines.push("");

  // AE 2022+ can't export H.264 directly — render to lossless AVI, ffmpeg converts later
  const outputAviPath = outputMp4Path.replace(/\.mp4$/i, "_ae_output.avi");

  // Declare outputFile before try block so it's accessible in cleanup
  lines.push(`var outputFile = new File("${escapeJsString(normalizePath(outputAviPath))}");`);
  lines.push("");

  // Wrap everything in a try-catch for error reporting
  lines.push("var _success = false;");
  lines.push("var _errorMsg = '';");
  lines.push("");
  lines.push("try {");
  lines.push("");

  // ── Open Project ──
  lines.push("  // ── Step 1: Open AEP Project ──");
  lines.push(
    `  var aepFile = new File("${escapeJsString(normalizePath(aepFilePath))}");`
  );
  lines.push("  if (!aepFile.exists) {");
  lines.push('    throw new Error("AEP file not found: " + aepFile.fsName);');
  lines.push("  }");
  lines.push("  var proj = app.open(aepFile);");
  lines.push("  if (!proj) {");
  lines.push('    throw new Error("Failed to open project");');
  lines.push("  }");
  lines.push("");

  // ── Set Variables on Controller Layers ──
  if (variables.length > 0) {
    lines.push(
      "  // ── Step 2: Set effect values on controller layers ──"
    );
    lines.push("");

    // Helper function to find a layer by name across all compositions
    lines.push("  function findLayerByName(name) {");
    lines.push(
      "    for (var c = 1; c <= app.project.numItems; c++) {"
    );
    lines.push("      var item = app.project.item(c);");
    lines.push("      if (item instanceof CompItem) {");
    lines.push(
      "        for (var l = 1; l <= item.numLayers; l++) {"
    );
    lines.push("          if (item.layer(l).name === name) {");
    lines.push("            return item.layer(l);");
    lines.push("          }");
    lines.push("        }");
    lines.push("      }");
    lines.push("    }");
    lines.push("    return null;");
    lines.push("  }");
    lines.push("");

    // Split variables into text layers (Source Text) and effect controls
    const textVars = variables.filter(
      (v) => v.effectType.toLowerCase() === "text"
    );
    const effectVars = variables.filter(
      (v) => v.effectType.toLowerCase() !== "text"
    );

    // ── Text layers (Source Text) ──
    if (textVars.length > 0) {
      lines.push("  // ── Set Source Text on text layers ──");
      for (const v of textVars) {
        const varName = sanitizeVarName(v.layerName);
        const escapedValue = escapeJsString(String(v.value));
        lines.push(`  // Text layer: ${v.layerName}`);
        lines.push(
          `  var textLayer_${varName} = findLayerByName("${escapeJsString(v.layerName)}");`
        );
        lines.push(`  if (textLayer_${varName} !== null) {`);
        lines.push("    try {");
        lines.push(
          `      var srcText = textLayer_${varName}.property("ADBE Text Properties").property("ADBE Text Document");`
        );
        lines.push("      if (srcText !== null) {");
        lines.push("        var textDoc = srcText.value;");
        lines.push(`        textDoc.text = "${escapedValue}";`);
        lines.push("        srcText.setValue(textDoc);");
        lines.push(
          `        $.writeln("Set text on layer '${escapeJsString(v.layerName)}': ${escapedValue}");`
        );
        lines.push("      }");
        lines.push("    } catch (e) {");
        lines.push(
          `      $.writeln("ERROR setting text on '${escapeJsString(v.layerName)}': " + e.message);`
        );
        lines.push("    }");
        lines.push("  } else {");
        lines.push(
          `    $.writeln("WARNING: Text layer '${escapeJsString(v.layerName)}' not found in project");`
        );
        lines.push("  }");
        lines.push("");
      }
    }

    // ── Effect controls (Slider, Checkbox, Color, etc.) ──
    // Group variables by layerName for efficiency
    const groupedByLayer = new Map<string, JsxVariable[]>();
    for (const v of effectVars) {
      const existing = groupedByLayer.get(v.layerName) || [];
      existing.push(v);
      groupedByLayer.set(v.layerName, existing);
    }

    for (const [layerName, layerVars] of groupedByLayer) {
      lines.push(`  // Controller: ${layerName}`);
      lines.push(
        `  var layer_${sanitizeVarName(layerName)} = findLayerByName("${escapeJsString(layerName)}");`
      );
      lines.push(
        `  if (layer_${sanitizeVarName(layerName)} !== null) {`
      );

      for (const v of layerVars) {
        const formattedValue = formatValue(v.effectType, v.value);
        const propertyName = getEffectPropertyName(v.effectType);
        lines.push(`    // Set ${v.effectName} (${v.effectType})`);
        lines.push("    try {");
        lines.push(
          `      var effect = layer_${sanitizeVarName(layerName)}.property("ADBE Effect Parade").property("${escapeJsString(v.effectName)}");`
        );
        lines.push("      if (effect !== null) {");
        lines.push(
          `        var prop = effect.property("${escapeJsString(propertyName)}");`
        );
        lines.push("        if (prop !== null) {");
        lines.push(`          prop.setValue(${formattedValue});`);
        lines.push("        } else {");
        lines.push(
          `          $.writeln("WARNING: Property '${escapeJsString(propertyName)}' not found on effect '${escapeJsString(v.effectName)}'");`
        );
        lines.push("        }");
        lines.push("      } else {");
        lines.push(
          `        $.writeln("WARNING: Effect '${escapeJsString(v.effectName)}' not found on layer '${escapeJsString(layerName)}'");`
        );
        lines.push("      }");
        lines.push("    } catch (e) {");
        lines.push(
          `      $.writeln("ERROR setting ${escapeJsString(v.effectName)}: " + e.message);`
        );
        lines.push("    }");
        lines.push("");
      }

      lines.push("  } else {");
      lines.push(
        `    $.writeln("WARNING: Layer '${escapeJsString(layerName)}' not found in project");`
      );
      lines.push("  }");
      lines.push("");
    }
  }

  // ── Replace Footage Items ──
  if (footageReplacements.length > 0) {
    lines.push("  // ── Step 3: Replace footage items ──");
    lines.push("");

    for (const replacement of footageReplacements) {
      lines.push(`  // Replace: ${replacement.originalName}`);
      lines.push("  (function() {");
      lines.push("    var found = false;");
      lines.push(
        "    for (var i = 1; i <= app.project.numItems; i++) {"
      );
      lines.push("      var item = app.project.item(i);");
      lines.push(
        '      if (item instanceof FootageItem && item.name === "' +
          escapeJsString(replacement.originalName) +
          '") {'
      );
      lines.push(
        `        var newFile = new File("${escapeJsString(normalizePath(replacement.newFilePath))}");`
      );
      lines.push("        if (newFile.exists) {");
      lines.push("          item.replace(newFile);");
      lines.push("          found = true;");
      lines.push(
        `          $.writeln("Replaced footage: ${escapeJsString(replacement.originalName)}");`
      );
      lines.push("        } else {");
      lines.push(
        '          $.writeln("WARNING: Replacement file not found: " + newFile.fsName);'
      );
      lines.push("        }");
      lines.push("        break;");
      lines.push("      }");
      lines.push("    }");
      lines.push("    if (!found) {");
      lines.push(
        `      $.writeln("WARNING: Footage item '${escapeJsString(replacement.originalName)}' not found in project");`
      );
      lines.push("    }");
      lines.push("  })();");
      lines.push("");
    }
  }

  // ── Save Modified Project ──
  lines.push("  // ── Step 4: Save modified AEP ──");
  lines.push(
    `  var outputAep = new File("${escapeJsString(normalizePath(outputAepPath))}");`
  );
  lines.push("  app.project.save(outputAep);");
  lines.push(
    '  $.writeln("Project saved to: " + outputAep.fsName);'
  );
  lines.push("");

  // ── Add to Render Queue ──
  lines.push(
    "  // ── Step 5: Add export composition to render queue ──"
  );
  lines.push("  var exportComp = null;");
  lines.push(
    "  for (var i = 1; i <= app.project.numItems; i++) {"
  );
  lines.push("    var item = app.project.item(i);");
  lines.push(
    `    if (item instanceof CompItem && item.name === "${escapeJsString(exportCompName)}") {`
  );
  lines.push("      exportComp = item;");
  lines.push("      break;");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  if (exportComp === null) {");
  lines.push(
    `    throw new Error("Export composition '${escapeJsString(exportCompName)}' not found");`
  );
  lines.push("  }");
  lines.push("");
  lines.push(
    "  var renderItem = app.project.renderQueue.items.add(exportComp);"
  );
  lines.push("");

  // ── Configure Output Module — lossless AVI (AE 2022+ dropped H.264 direct export) ──
  lines.push("  // ── Step 6: Configure output module (lossless AVI for ffmpeg conversion) ──");
  lines.push("  var outputModule = renderItem.outputModule(1);");
  lines.push("");
  lines.push("  // Try lossless templates in order of preference");
  lines.push("  var losslessTemplates = [");
  lines.push('    "Lossless",');
  lines.push('    "Lossless with Alpha",');
  lines.push('    "AVI (Uncompressed)",');
  lines.push('    "Animation",');
  lines.push('    "PNG Sequence"');
  lines.push("  ];");
  lines.push("");
  lines.push("  var templateApplied = false;");
  lines.push("  for (var t = 0; t < losslessTemplates.length; t++) {");
  lines.push("    try {");
  lines.push("      outputModule.applyTemplate(losslessTemplates[t]);");
  lines.push("      templateApplied = true;");
  lines.push('      $.writeln("Applied output template: " + losslessTemplates[t]);');
  lines.push("      break;");
  lines.push("    } catch (e) {");
  lines.push("      // Template not available, try next");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  if (!templateApplied) {");
  lines.push('    $.writeln("WARNING: No lossless template found, using default.");');
  lines.push("    var templates = outputModule.templates;");
  lines.push('    $.writeln("Available templates:");');
  lines.push("    for (var ti = 0; ti < templates.length; ti++) {");
  lines.push('      $.writeln("  - " + templates[ti]);');
  lines.push("    }");
  lines.push("  }");
  lines.push("");

  // Set output file path
  lines.push("  // Set output file (outputFile declared above try block)");
  lines.push("  outputModule.file = outputFile;");
  lines.push(
    '  $.writeln("Output file set to: " + outputFile.fsName);'
  );
  lines.push("");

  // ── Start Render ──
  lines.push("  // ── Step 7: Start render ──");
  lines.push('  $.writeln("Starting render...");');
  lines.push("  app.project.renderQueue.render();");
  lines.push('  $.writeln("Render complete.");');
  lines.push("");
  lines.push("  _success = true;");
  lines.push("");

  // ── Error Handling ──
  lines.push("} catch (err) {");
  lines.push('  _errorMsg = "RENDER ERROR: " + err.message;');
  lines.push("  $.writeln(_errorMsg);");
  lines.push("  _success = false;");
  lines.push("}");
  lines.push("");

  // ── Cleanup & Quit ──
  lines.push("// ── Step 8: Cleanup and quit ──");
  lines.push("app.endSuppressDialogs(false);");
  lines.push("");
  lines.push("// Write result status for the agent to parse");
  lines.push(
    'var statusFile = new File(outputFile.parent.fsName + "/render_status.txt");'
  );
  lines.push('statusFile.open("w");');
  lines.push("if (_success) {");
  lines.push('  statusFile.writeln("SUCCESS");');
  lines.push("} else {");
  lines.push('  statusFile.writeln("FAILED");');
  lines.push("  statusFile.writeln(_errorMsg);");
  lines.push("}");
  lines.push("statusFile.close();");
  lines.push("");
  lines.push("// Quit After Effects");
  lines.push("app.quit();");
  lines.push("");

  return lines.join("\n");
}

// ─── Wrapper for JobProcessor ───────────────────────────
// Maps RenderJob data to JsxGeneratorInput and calls generateJsx()

export function buildJsx(
  job: RenderJob,
  aepPath: string,
  outputAepPath: string,
  outputMp4Path: string,
  footageReplacements: JsxFootageReplacement[]
): string {
  const variables: JsxVariable[] = [];

  // Map job data to variables
  for (const data of job.jobData) {
    const templateVar = job.template.variables.find(
      (v) => v.id === data.key
    );
    if (templateVar) {
      let value: string | number = data.value;
      if (
        templateVar.effectType === "Slider" ||
        templateVar.type === "SLIDER"
      ) {
        value = parseFloat(data.value) || 0;
      } else if (
        templateVar.effectType === "Checkbox" ||
        templateVar.type === "CHECKBOX"
      ) {
        value = data.value === "1" ? 1 : 0;
      }
      variables.push({
        layerName: templateVar.layerName,
        effectName: templateVar.effectName,
        effectType: templateVar.effectType,
        value,
      });
    }
  }

  return generateJsx({
    aepFilePath: aepPath,
    outputAepPath,
    outputMp4Path,
    exportCompName: job.template.exportCompName,
    variables,
    footageReplacements,
  });
}
