// ─── JSX Generator for After Effects ExtendScript ───────
// Generates .jsx scripts that After Effects can execute via aerender
// to open a project, set variable values, replace footage, render, and quit.

// ─── Types ──────────────────────────────────────────────

export interface JsxVariable {
  layerName: string;
  effectName: string;
  effectType: string;
  value: string | number;
}

export interface JsxFootageReplacement {
  originalName: string;
  newFilePath: string;
}

export interface JsxGeneratorInput {
  aepFilePath: string;
  outputAepPath: string;
  outputMp4Path: string;
  exportCompName: string;
  variables: JsxVariable[];
  footageReplacements: JsxFootageReplacement[];
}

// ─── Helpers ────────────────────────────────────────────

/**
 * Escape a string for use inside a JavaScript/ExtendScript string literal.
 * Handles backslashes (common in Windows paths), quotes, and newlines.
 */
function escapeJsString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/'/g, "\\'")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

/**
 * Convert a file path to use forward slashes (ExtendScript File objects
 * accept both, but forward slashes are safer cross-platform).
 */
function normalizePath(p: string): string {
  return p.replace(/\\/g, "/");
}

/**
 * Generate the value assignment expression depending on the effect type.
 * Slider values are numbers, Checkbox values are booleans (0/1).
 */
function formatValue(effectType: string, value: string | number): string {
  switch (effectType.toLowerCase()) {
    case "slider":
      return typeof value === "number" ? String(value) : `parseFloat("${escapeJsString(String(value))}")`;
    case "checkbox":
      // Checkbox Control values are 0 (unchecked) or 1 (checked).
      // Accept boolean-like strings as well.
      if (typeof value === "number") return value ? "1" : "0";
      if (typeof value === "string") {
        const lower = value.toLowerCase();
        if (lower === "true" || lower === "1" || lower === "yes" || lower === "on") return "1";
        if (lower === "false" || lower === "0" || lower === "no" || lower === "off") return "0";
        return `parseInt("${escapeJsString(value)}", 10)`;
      }
      return String(value);
    case "color":
      // Color values are arrays like [r, g, b, a] with values 0-1
      return String(value);
    default:
      return typeof value === "number" ? String(value) : `"${escapeJsString(String(value))}"`;
  }
}

// ─── JSX Code Generation ────────────────────────────────

/**
 * Generate an ExtendScript (.jsx) file content that After Effects can execute.
 *
 * The generated script performs these operations in order:
 * 1. Suppresses all dialogs and UI
 * 2. Opens the AEP project file
 * 3. Iterates through compositions to find controller layers
 * 4. Sets effect values (Slider Control, Checkbox Control, etc.) on controller layers
 * 5. Replaces footage items with new files
 * 6. Saves the modified AEP to a new location
 * 7. Adds the export composition to the render queue
 * 8. Configures the output module for MP4 (H.264)
 * 9. Starts the render
 * 10. Quits After Effects
 *
 * @param input - Configuration for the JSX generation
 * @returns Complete ExtendScript code as a string
 */
export function generateJsx(input: JsxGeneratorInput): string {
  const {
    aepFilePath,
    outputAepPath,
    outputMp4Path,
    exportCompName,
    variables,
    footageReplacements,
  } = input;

  const lines: string[] = [];

  // ── Header & Error Handling ──
  lines.push("// Auto-generated ExtendScript for After Effects");
  lines.push("// Generated by AE Render Automat");
  lines.push(`// Date: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("// Suppress all dialogs");
  lines.push("app.beginSuppressDialogs();");
  lines.push("");

  // Wrap everything in a try-catch for error reporting
  lines.push("var _success = false;");
  lines.push("var _errorMsg = '';");
  lines.push("");
  lines.push("try {");
  lines.push("");

  // ── Open Project ──
  lines.push("  // ── Step 1: Open AEP Project ──");
  lines.push(`  var aepFile = new File("${escapeJsString(normalizePath(aepFilePath))}");`);
  lines.push("  if (!aepFile.exists) {");
  lines.push(`    throw new Error("AEP file not found: " + aepFile.fsName);`);
  lines.push("  }");
  lines.push("  var proj = app.open(aepFile);");
  lines.push("  if (!proj) {");
  lines.push(`    throw new Error("Failed to open project");`);
  lines.push("  }");
  lines.push("");

  // ── Set Variables on Controller Layers ──
  if (variables.length > 0) {
    lines.push("  // ── Step 2: Set effect values on controller layers ──");
    lines.push("");

    // Helper function to find a layer by name across all compositions
    lines.push("  function findLayerByName(name) {");
    lines.push("    for (var c = 1; c <= app.project.numItems; c++) {");
    lines.push("      var item = app.project.item(c);");
    lines.push('      if (item instanceof CompItem) {');
    lines.push("        for (var l = 1; l <= item.numLayers; l++) {");
    lines.push("          if (item.layer(l).name === name) {");
    lines.push("            return item.layer(l);");
    lines.push("          }");
    lines.push("        }");
    lines.push("      }");
    lines.push("    }");
    lines.push("    return null;");
    lines.push("  }");
    lines.push("");

    // Split variables into text layers (Source Text) and effect controls
    const textVars = variables.filter((v) => v.effectType.toLowerCase() === "text");
    const effectVars = variables.filter((v) => v.effectType.toLowerCase() !== "text");

    // ── Text layers (Source Text) ──
    if (textVars.length > 0) {
      lines.push("  // ── Set Source Text on text layers ──");
      for (const v of textVars) {
        const varName = sanitizeVarName(v.layerName);
        const escapedValue = escapeJsString(String(v.value));
        lines.push(`  // Text layer: ${v.layerName}`);
        lines.push(`  var textLayer_${varName} = findLayerByName("${escapeJsString(v.layerName)}");`);
        lines.push(`  if (textLayer_${varName} !== null) {`);
        lines.push("    try {");
        lines.push(`      var srcText = textLayer_${varName}.property("ADBE Text Properties").property("ADBE Text Document");`);
        lines.push("      if (srcText !== null) {");
        lines.push(`        var textDoc = srcText.value;`);
        lines.push(`        textDoc.text = "${escapedValue}";`);
        lines.push(`        srcText.setValue(textDoc);`);
        lines.push(`        $.writeln("Set text on layer '${escapeJsString(v.layerName)}': ${escapedValue}");`);
        lines.push("      }");
        lines.push("    } catch (e) {");
        lines.push(`      $.writeln("ERROR setting text on '${escapeJsString(v.layerName)}': " + e.message);`);
        lines.push("    }");
        lines.push("  } else {");
        lines.push(`    $.writeln("WARNING: Text layer '${escapeJsString(v.layerName)}' not found in project");`);
        lines.push("  }");
        lines.push("");
      }
    }

    // ── Effect controls (Slider, Checkbox, Color, etc.) ──
    // Group variables by layerName for efficiency
    const groupedByLayer = new Map<string, JsxVariable[]>();
    for (const v of effectVars) {
      const existing = groupedByLayer.get(v.layerName) || [];
      existing.push(v);
      groupedByLayer.set(v.layerName, existing);
    }

    for (const [layerName, layerVars] of groupedByLayer) {
      lines.push(`  // Controller: ${layerName}`);
      lines.push(`  var layer_${sanitizeVarName(layerName)} = findLayerByName("${escapeJsString(layerName)}");`);
      lines.push(`  if (layer_${sanitizeVarName(layerName)} !== null) {`);

      for (const v of layerVars) {
        const formattedValue = formatValue(v.effectType, v.value);
        lines.push(`    // Set ${v.effectName} (${v.effectType})`);
        lines.push("    try {");
        lines.push(
          `      var effect = layer_${sanitizeVarName(layerName)}.property("ADBE Effect Parade").property("${escapeJsString(v.effectName)}");`
        );
        lines.push("      if (effect !== null) {");

        // Determine the property name based on effect type
        const propertyName = getEffectPropertyName(v.effectType);
        lines.push(
          `        var prop = effect.property("${escapeJsString(propertyName)}");`
        );
        lines.push("        if (prop !== null) {");
        lines.push(`          prop.setValue(${formattedValue});`);
        lines.push("        } else {");
        lines.push(
          `          $.writeln("WARNING: Property '${escapeJsString(propertyName)}' not found on effect '${escapeJsString(v.effectName)}'");`
        );
        lines.push("        }");
        lines.push("      } else {");
        lines.push(
          `        $.writeln("WARNING: Effect '${escapeJsString(v.effectName)}' not found on layer '${escapeJsString(layerName)}'");`
        );
        lines.push("      }");
        lines.push("    } catch (e) {");
        lines.push(
          `      $.writeln("ERROR setting ${escapeJsString(v.effectName)}: " + e.message);`
        );
        lines.push("    }");
        lines.push("");
      }

      lines.push("  } else {");
      lines.push(
        `    $.writeln("WARNING: Layer '${escapeJsString(layerName)}' not found in project");`
      );
      lines.push("  }");
      lines.push("");
    }
  }

  // ── Replace Footage Items ──
  if (footageReplacements.length > 0) {
    lines.push("  // ── Step 3: Replace footage items ──");
    lines.push("");

    for (const replacement of footageReplacements) {
      lines.push(`  // Replace: ${replacement.originalName}`);
      lines.push("  (function() {");
      lines.push("    var found = false;");
      lines.push("    for (var i = 1; i <= app.project.numItems; i++) {");
      lines.push("      var item = app.project.item(i);");
      lines.push(
        '      if (item instanceof FootageItem && item.name === "' +
          escapeJsString(replacement.originalName) +
          '") {'
      );
      lines.push(
        `        var newFile = new File("${escapeJsString(normalizePath(replacement.newFilePath))}");`
      );
      lines.push("        if (newFile.exists) {");
      lines.push("          item.replace(newFile);");
      lines.push("          found = true;");
      lines.push(
        `          $.writeln("Replaced footage: ${escapeJsString(replacement.originalName)}");`
      );
      lines.push("        } else {");
      lines.push(
        `          $.writeln("WARNING: Replacement file not found: " + newFile.fsName);`
      );
      lines.push("        }");
      lines.push("        break;");
      lines.push("      }");
      lines.push("    }");
      lines.push("    if (!found) {");
      lines.push(
        `      $.writeln("WARNING: Footage item '${escapeJsString(replacement.originalName)}' not found in project");`
      );
      lines.push("    }");
      lines.push("  })();");
      lines.push("");
    }
  }

  // ── Save Modified Project ──
  lines.push("  // ── Step 4: Save modified AEP ──");
  lines.push(
    `  var outputAep = new File("${escapeJsString(normalizePath(outputAepPath))}");`
  );
  lines.push("  app.project.save(outputAep);");
  lines.push(
    `  $.writeln("Project saved to: " + outputAep.fsName);`
  );
  lines.push("");

  // ── Add to Render Queue ──
  lines.push("  // ── Step 5: Add export composition to render queue ──");
  lines.push("  var exportComp = null;");
  lines.push("  for (var i = 1; i <= app.project.numItems; i++) {");
  lines.push("    var item = app.project.item(i);");
  lines.push(
    `    if (item instanceof CompItem && item.name === "${escapeJsString(exportCompName)}") {`
  );
  lines.push("      exportComp = item;");
  lines.push("      break;");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  if (exportComp === null) {");
  lines.push(
    `    throw new Error("Export composition '${escapeJsString(exportCompName)}' not found");`
  );
  lines.push("  }");
  lines.push("");
  lines.push("  var renderItem = app.project.renderQueue.items.add(exportComp);");
  lines.push("");

  // ── Configure Output Module for MP4 (H.264) ──
  lines.push("  // ── Step 6: Configure output module ──");
  lines.push("  var outputModule = renderItem.outputModule(1);");
  lines.push("");
  lines.push("  // Try to apply H.264 output template, fall back to available templates");
  lines.push("  var mp4Templates = [");
  lines.push('    "H.264 - Match Render Settings - 15 Mbps",');
  lines.push('    "H.264 - Match Render Settings - 10 Mbps",');
  lines.push('    "H.264 - Match Render Settings",');
  lines.push('    "H.264",');
  lines.push('    "H.264 - Match Render Settings - High Quality"');
  lines.push("  ];");
  lines.push("");
  lines.push("  var templateApplied = false;");
  lines.push("  for (var t = 0; t < mp4Templates.length; t++) {");
  lines.push("    try {");
  lines.push("      outputModule.applyTemplate(mp4Templates[t]);");
  lines.push("      templateApplied = true;");
  lines.push('      $.writeln("Applied output template: " + mp4Templates[t]);');
  lines.push("      break;");
  lines.push("    } catch (e) {");
  lines.push("      // Template not available, try next");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  if (!templateApplied) {");
  lines.push('    $.writeln("WARNING: No H.264 template found. Using default output module.");');
  lines.push("    // List available templates for debugging");
  lines.push("    var templates = outputModule.templates;");
  lines.push('    $.writeln("Available templates:");');
  lines.push("    for (var ti = 0; ti < templates.length; ti++) {");
  lines.push('      $.writeln("  - " + templates[ti]);');
  lines.push("    }");
  lines.push("  }");
  lines.push("");

  // Set output file path
  lines.push("  // Set output file");
  lines.push(
    `  var outputFile = new File("${escapeJsString(normalizePath(outputMp4Path))}");`
  );
  lines.push("  outputModule.file = outputFile;");
  lines.push(
    `  $.writeln("Output file set to: " + outputFile.fsName);`
  );
  lines.push("");

  // ── Start Render ──
  lines.push("  // ── Step 7: Start render ──");
  lines.push('  $.writeln("Starting render...");');
  lines.push("  app.project.renderQueue.render();");
  lines.push('  $.writeln("Render complete.");');
  lines.push("");
  lines.push("  _success = true;");
  lines.push("");

  // ── Error Handling ──
  lines.push("} catch (err) {");
  lines.push('  _errorMsg = "RENDER ERROR: " + err.message;');
  lines.push("  $.writeln(_errorMsg);");
  lines.push("  _success = false;");
  lines.push("}");
  lines.push("");

  // ── Cleanup & Quit ──
  lines.push("// ── Step 8: Cleanup and quit ──");
  lines.push("app.endSuppressDialogs(false);");
  lines.push("");
  lines.push("// Write result status for the agent to parse");
  lines.push('var statusFile = new File(outputFile.parent.fsName + "/render_status.txt");');
  lines.push('statusFile.open("w");');
  lines.push("if (_success) {");
  lines.push('  statusFile.writeln("SUCCESS");');
  lines.push("} else {");
  lines.push('  statusFile.writeln("FAILED");');
  lines.push("  statusFile.writeln(_errorMsg);");
  lines.push("}");
  lines.push("statusFile.close();");
  lines.push("");
  lines.push("// Quit After Effects");
  lines.push("app.quit();");
  lines.push("");

  return lines.join("\n");
}

// ─── Internal Helpers ───────────────────────────────────

/**
 * Sanitize a layer name for use as a JavaScript variable name.
 * Replaces non-alphanumeric characters with underscores.
 */
function sanitizeVarName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^(\d)/, "_$1")
    .replace(/_+/g, "_")
    .replace(/_$/, "");
}

/**
 * Get the AE property name for a given effect type.
 * In After Effects, each expression control has a specific property name.
 */
function getEffectPropertyName(effectType: string): string {
  switch (effectType.toLowerCase()) {
    case "slider":
      return "Slider";
    case "checkbox":
      return "Checkbox";
    case "color":
      return "Color";
    case "point":
      return "Point";
    case "layer":
      return "Layer";
    case "angle":
      return "Angle";
    case "dropdown":
      return "Menu";
    default:
      return effectType;
  }
}
